# Generated by Django 2.0 on 2017-12-07 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DepName', models.CharField(max_length=50)),
                ('DepHead', models.CharField(max_length=100)),
                ('DepTel', models.CharField(max_length=20)),
                ('DepEmail', models.CharField(max_length=500)),
                ('Dep_logo', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('Degree', models.CharField(max_length=200)),
                ('DOB', models.CharField(max_length=200)),
                ('Tel', models.CharField(max_length=200)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Department')),
            ],
        ),
    ]
