# Generated by Django 2.0 on 2017-12-08 16:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_remove_department_dep_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='Dep_logo',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
