# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-09 13:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_auto_20171209_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='StudentID',
            field=models.CharField(default='xxxxxxxxxx', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.ForeignKey(default='DEP', on_delete=django.db.models.deletion.CASCADE, to='student.Department'),
        ),
    ]
