# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-09 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_auto_20171209_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='status',
        ),
        migrations.AddField(
            model_name='student',
            name='Address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='CurrentSemester',
            field=models.CharField(default='X/YYYY', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='Curriculum',
            field=models.CharField(default='CURRICULUM NAME', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='DepNo',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AddField(
            model_name='student',
            name='Email',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='GPAX',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Status',
            field=models.CharField(default='Normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='DOB',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='Degree',
            field=models.CharField(default='DEG', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='StudentID',
            field=models.CharField(default='xxxxxxxxxx', max_length=11),
        ),
        migrations.AlterField(
            model_name='student',
            name='Tel',
            field=models.CharField(default='TEL', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(default='NAME', max_length=50),
        ),
    ]
