# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-09 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_auto_20171210_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Email',
            field=models.CharField(blank=True, default=None, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Tel',
            field=models.CharField(blank=True, default='TEL', max_length=12, null=True),
        ),
    ]
