# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-09 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_auto_20171210_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='StudentID',
            field=models.CharField(max_length=11),
        ),
    ]
