# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-09 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_remove_student_depno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='Section',
        ),
        migrations.AddField(
            model_name='subject',
            name='Credit',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='subject',
            name='Prerequisite',
            field=models.CharField(blank=True, default=None, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='Semester',
            field=models.CharField(default='X/YYYY', max_length=20),
        ),
        migrations.AlterField(
            model_name='subject',
            name='SubjectID',
            field=models.CharField(max_length=8),
        ),
    ]
