# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-10 05:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0019_auto_20171210_0224'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudyYet', models.BooleanField()),
                ('Grade', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name='student',
            old_name='department',
            new_name='stu_dep_FK',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='subjectFK',
            new_name='sub_student_FK',
        ),
        migrations.AddField(
            model_name='history',
            name='his_student_FK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
        ),
        migrations.AddField(
            model_name='history',
            name='his_subject_FK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Subject'),
        ),
    ]
