# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-10 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0020_auto_20171210_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='Grade',
            field=models.CharField(max_length=2),
        ),
    ]
