# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-10 08:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0022_remove_subject_sub_student_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SectionNo', models.CharField(max_length=2)),
                ('TotalSeat', models.IntegerField()),
                ('LessonTime', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='sub_sec_FK',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.Section'),
        ),
    ]
