# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-10 08:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0023_auto_20171210_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='sec_subject_FK',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.Subject'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='sub_sec_FK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.Section'),
        ),
    ]
