# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-10 09:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0024_auto_20171210_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LecturerID', models.CharField(max_length=11)),
                ('LecturerName', models.CharField(max_length=50)),
                ('LecturerAddress', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('LecturerTel', models.CharField(blank=True, default=None, max_length=12, null=True)),
                ('LecturerRating', models.FloatField()),
                ('LecturerEmail', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('lec_dep_FK', models.ForeignKey(default='DEP', on_delete=django.db.models.deletion.CASCADE, to='student.Department')),
            ],
        ),
    ]
