# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-10 09:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0026_advisor'),
    ]

    operations = [
        migrations.CreateModel(
            name='LecturerInSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('lecsec_lec_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Lecturer')),
                ('lecsec_sec_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Section')),
                ('lecsec_sub_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Subject')),
            ],
        ),
    ]
