# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-10 10:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0027_lecturerinsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='LecturerResearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ResearchName', models.CharField(max_length=30)),
                ('Category', models.CharField(max_length=20)),
                ('Description', models.CharField(max_length=150)),
                ('reser_lec_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Lecturer')),
            ],
        ),
    ]
