# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-10 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0029_curriculum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecturerresearch',
            old_name='reser_lec_FK',
            new_name='research_lec_FK',
        ),
        migrations.AddField(
            model_name='lecturer',
            name='LecturerProfile',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
