# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-10 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0030_auto_20171211_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='LecturerDegree',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
