# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-10 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0032_auto_20171211_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='Cost',
            field=models.FloatField(),
        ),
    ]
