# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-10 18:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0033_auto_20171211_0117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreditRequire', models.IntegerField()),
                ('Semester', models.CharField(default='X/YYYY', max_length=20)),
                ('cre_cur_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Curriculum')),
            ],
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='LecturerRating',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
