# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-10 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0034_auto_20171211_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='thYear',
            field=models.CharField(default='-', max_length=1),
        ),
    ]
