# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-10 22:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0039_auto_20171211_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturerresearch',
            name='research_lec_FK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Lecturer'),
        ),
    ]
