# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-11 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0040_auto_20171211_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='StudentProfile',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
