# Generated by Django 2.0 on 2017-12-08 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20171208_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='Dep_logo',
        ),
    ]
