# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-09 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_auto_20171210_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='DepNo',
            field=models.CharField(default='xxxx', max_length=4),
        ),
        migrations.AlterField(
            model_name='department',
            name='DepEmail',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='department',
            name='DepHead',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='department',
            name='DepName',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='department',
            name='DepTel',
            field=models.CharField(max_length=12),
        ),
    ]
