# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-10 18:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0029_curriculum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegNo', models.CharField(max_length=15)),
                ('Date', models.DateField()),
                ('Cost', models.DateField()),
                ('Discount', models.FloatField()),
                ('PaymentMethod', models.CharField(max_length=10)),
                ('PaymentStatus', models.CharField(max_length=10)),
                ('PaymentDate', models.DateField()),
                ('Semester', models.CharField(default='X/YYYY', max_length=20)),
                ('reg_stu_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
                ('stu_dep_FK', models.ForeignKey(default='DEP', on_delete=django.db.models.deletion.CASCADE, to='student.Department')),
            ],
        ),
    ]
