# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-10 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0031_remove_register_stu_dep_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='PaymentDate',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
