# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-10 19:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0032_auto_20171211_0123'),
        ('student', '0035_credit_thyear'),
    ]

    operations = [
    ]
