# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-10 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0037_auto_20171211_0449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='LecturerID',
            field=models.CharField(max_length=11),
        ),
    ]
